### ISSUE TITLE
Activity ID: CS0029  C# Cannot implicitly convert type 'System.Uri' to 'string'

### ISSUE THREAD

**Issue by AnnabellBrocker** [RusticiSoftware/TinCan.NET#46]
When I want to add an id to an activity, I get this error:
CS0029  C# Cannot implicitly convert type 'System.Uri' to 'string'

Seems to be some wrong implementations for activity id. Id for Verb is okay, but not for activity.

**Comment by reedmclean** [comment]
Hello!

What value are you trying to set the activity ID to? xAPI activity IDs should be IRIs (detailed in the spec here: https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Communication.md#25-activities-resource), which is the reason we use the `Uri` constructor here: https://github.com/RusticiSoftware/TinCan.NET/blob/master/TinCan/Activity.cs#L33.

I would expect a slightly different error if the exception was being thrown during `Uri` construction... Could you post a sample of the code you're trying or a stack trace of the error you're receiving?

**Comment by AnnabellBrocker** [comment]
So I basically did the following (the same as in your example http://rusticisoftware.github.io/TinCan.NET/):

var activity = new Activity();
activity.id = new Uri("http://thisIsATestURI");

There I directly get the error of Visual Studio:
Error	CS0029	Cannot implicitly convert type 'System.Uri' to 'string'

When doing the same for a verb, it is working:
var verb = new Verb();
verb.id = new Uri("http://thisIsATestURI");

**Comment by reedmclean** [comment]
`Activity.id` is a `string`(https://github.com/RusticiSoftware/TinCan.NET/blob/master/TinCan/Activity.cs#L28) while `Verb.id` is a `Uri` (https://github.com/RusticiSoftware/TinCan.NET/blob/master/TinCan/Verb.cs#L24). Try

```
activity.id = "http://thisIsATestURI";
```

That inconsistency is due to some normalization that the `Uri` constructor does. You can read about it in this commit message: https://github.com/RusticiSoftware/TinCan.NET/commit/0cc73f0eff2682451f4ec4f67e17befe01a8c432 We initialize a `Uri` in the setter to ensure that the incoming value is formatted correctly, but we interact with the value as a `string` to avoid the unintentional changes that the `Uri` constructor will make.

It looks like the example just wasn't updated to match this change. Sorry for the confusion there.

**Comment by AnnabellBrocker** [comment]
Alright thanks for your responds :)
